<?php

namespace App\Constraint;

use Attribute;
use Symfony\Component\Validator\Constraint;

#[Attribute]
class CorrectExpressionLanguageConstraint extends Constraint
{

    public function getTargets(): array|string
    {
        return self::CLASS_CONSTRAINT; // TODO: Change the autogenerated stub
    }
}