version: '3.3'

services:
    database:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root
            MYSQL_DATABASE: cortest
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - database
        ports:
            - "8081:80"
        environment:  # Same as database service
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: mysql
            PMA_PASSWORD: mysql
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - database
volumes:
    data: