version: '3.8'

services:
    database:
        container_name: mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root
            MYSQL_DATABASE: cortest
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        ports:
            - "4306:3306"
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - database