<?php
/**
 * ReponsesACorrigerInnerTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApiBundle\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * API Cortest
 *
 * API Cortest
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace App\OpenApiBundle\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ReponsesACorrigerInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ReponsesACorrigerInner
 * @package     App\OpenApiBundle\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \App\OpenApiBundle\Model\ReponsesACorrigerInner
 */
class ReponsesACorrigerInnerTest extends TestCase
{
    protected ReponsesACorrigerInner|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(ReponsesACorrigerInner::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(ReponsesACorrigerInner::class));
        $this->assertInstanceOf(ReponsesACorrigerInner::class, $this->object);
    }

    /**
     * Test attribute "value"
     *
     * @group unit
     * @small
     */
    public function testPropertyValue(): void
    {
        $this->markTestSkipped('Test for property value not implemented');
    }
}
