<?php
/**
 * ReponsesACorriger
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApiBundle\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * API Cortest
 *
 * API Cortest
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApiBundle\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ReponsesACorriger model.
 *
 * @package App\OpenApiBundle\Model
 * @author  OpenAPI Generator team
 */
class ReponsesACorriger 
{
        /**
     * @var array|null
     * @SerializedName("reponses")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $reponses = null;

    /**
     * @var int|null
     * @SerializedName("sessionID")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $sessionID = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->reponses = $data['reponses'] ?? null;
        $this->sessionID = $data['sessionID'] ?? null;
    }

    /**
     * Gets reponses.
     *
     * @return array|null
     */
    public function getReponses(): ?array
    {
        return $this->reponses;
    }

    /**
     * Sets reponses.
     *
     * @param array|null $reponses
     *
     * @return $this
     */
    public function setReponses(?array $reponses): self
    {
        $this->reponses = $reponses;

        return $this;
    }

    /**
     * Gets sessionID.
     *
     * @return int|null
     */
    public function getSessionID(): ?int
    {
        return $this->sessionID;
    }

    /**
     * Sets sessionID.
     *
     * @param int|null $sessionID
     *
     * @return $this
     */
    public function setSessionID(?int $sessionID): self
    {
        $this->sessionID = $sessionID;

        return $this;
    }
}


