<?php
/**
 * ScoresACalculer
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApiBundle\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * API Cortest
 *
 * API Cortest
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApiBundle\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ScoresACalculer model.
 *
 * @package App\OpenApiBundle\Model
 * @author  OpenAPI Generator team
 */
class ScoresACalculer 
{
        /**
     * @var array|null
     * @SerializedName("reponses")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected ?array $reponses = null;

    /**
     * @var int|null
     * @SerializedName("score_computer_ID")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $scoreComputerID = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->reponses = $data['reponses'] ?? null;
        $this->scoreComputerID = $data['scoreComputerID'] ?? null;
    }

    /**
     * Gets reponses.
     *
     * @return array|null
     */
    public function getReponses(): ?array
    {
        return $this->reponses;
    }

    /**
     * Sets reponses.
     *
     * @param array|null $reponses
     *
     * @return $this
     */
    public function setReponses(?array $reponses = null): self
    {
        $this->reponses = $reponses;

        return $this;
    }

    /**
     * Gets scoreComputerID.
     *
     * @return int|null
     */
    public function getScoreComputerID(): ?int
    {
        return $this->scoreComputerID;
    }

    /**
     * Sets scoreComputerID.
     *
     * @param int|null $scoreComputerID
     *
     * @return $this
     */
    public function setScoreComputerID(?int $scoreComputerID = null): self
    {
        $this->scoreComputerID = $scoreComputerID;

        return $this;
    }
}


