<?php
/**
 * DefaultApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\OpenApiBundle
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * API Cortest
 *
 * API Cortest
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApiBundle\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApiBundle\Model\ReponsesACalculer;
use App\OpenApiBundle\Model\ScoresACalculer;

/**
 * DefaultApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApiBundle\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface DefaultApiInterface
{

    /**
     * Operation calculerReponsesPost
     *
     * @param  ReponsesACalculer|null $reponsesACalculer   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function calculerReponsesPost(?ReponsesACalculer $reponsesACalculer, int &$responseCode, array &$responseHeaders): void;


    /**
     * Operation calculerScoresPost
     *
     * @param  ScoresACalculer|null $scoresACalculer   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function calculerScoresPost(?ScoresACalculer $scoresACalculer, int &$responseCode, array &$responseHeaders): void;

}
