/**
 * API Cortest
 * API Cortest
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScoresACalculer model module.
 * @module model/ScoresACalculer
 * @version 1.0.0
 */
class ScoresACalculer {
    /**
     * Constructs a new <code>ScoresACalculer</code>.
     * @alias module:model/ScoresACalculer
     */
    constructor() { 
        
        ScoresACalculer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScoresACalculer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScoresACalculer} obj Optional instance to populate.
     * @return {module:model/ScoresACalculer} The populated <code>ScoresACalculer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoresACalculer();

            if (data.hasOwnProperty('reponses')) {
                obj['reponses'] = ApiClient.convertToType(data['reponses'], ['Number']);
            }
            if (data.hasOwnProperty('score_computer_ID')) {
                obj['score_computer_ID'] = ApiClient.convertToType(data['score_computer_ID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScoresACalculer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScoresACalculer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['reponses'])) {
            throw new Error("Expected the field `reponses` to be an array in the JSON data but got " + data['reponses']);
        }

        return true;
    }


}



/**
 * @member {Array.<Number>} reponses
 */
ScoresACalculer.prototype['reponses'] = undefined;

/**
 * @member {Number} score_computer_ID
 */
ScoresACalculer.prototype['score_computer_ID'] = undefined;






export default ScoresACalculer;

